snipps/app/urls.py
from django.urls import path

from . import views

app_name = 'app'


"""
LINQS URLS
"""
urlpatterns = [
    path('', views.home, name='home'),

    # Linqs main page
    path('linqs/', views.linqs, name='linqs'),

    # Categories API
    path('api/linqs/add_category', views.add_category, name='add-category'),
    path('api/linqs/get_category_linqs', views.category_linqs, name='get-category-linqs'),
    path('api/linqs/delete_category', views.archive_category, name='archive-category'),

    # Linqs API
    path('api/linqs/add', views.add_linq, name='add-linq'),
    path('api/linqs/delete_linq', views.archive_linq, name='archive-linq'),
    path('api/linqs/search', views.search_linq, name='search-linq'),
]


"""
SNIPPETS URLS
"""
urlpatterns = urlpatterns + [
    # Snippets
    path('snippets/', views.snippets, name='snippets'),

    # Snippets API
]

snipps/snipps/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from app.forms import LoginForm

urlpatterns = [
    # app
    path('', include('app.urls')),

    # django admin
    path('admin/', admin.site.urls),

    # auth
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

snipps/app/views/linqs_views.py
from django.contrib.auth.decorators import login_required
# from django.db import connection
from django.http import JsonResponse
from django.shortcuts import render, redirect
from rest_framework import status
from rest_framework.decorators import api_view

from app.models import Category, LinqLabel, LinqUrl
from app.caches.linqs_cache import LinqsCache
from app.serializers import CategorySerializer, LinqLabelSerializer
from app.utils import SuccessJsonResponse


@login_required
def home(request):
    return redirect('app:linqs')


@login_required
def linqs(request):
    """
    Renders the initial page with the default selected values
    """

    categories = Category.objects.filter(user=request.user)
    initial_category_id = categories[0].id

    context = {
        'init_js_data': {
            'categories': CategorySerializer(categories, many=True).data
        }
    }

    if categories:
        serialized_linq_list = LinqsCache(initial_category_id).serialized_objects()

        context['init_js_data'].update({
            'initSelectedLinqs': serialized_linq_list
        })

    # for reference, =)
    # selected = categories.filter(pk=categories[0].id).prefetch_related('linqlabel_set', 'linqlabel_set__linqurl_set').get()
    # 'initSelectedLinqs': LinqLabelSerializer(instance=linq_list_qs, many=True).data  # 'instance=' is optional

    return render(request, 'app/linqs.html', context)


# API VIEWS
@login_required
@api_view(['POST'])
def add_category(request):
    """
    Add a new category
    """

    category_count = Category.objects.count()
    data = {'user': request.user.id, **request.data}

    # only when creating a category for the firs time
    if category_count == 0:
        data.update({'new_item': False})

    category_serializer = CategorySerializer(data=data)

    if category_serializer.is_valid():
        category_serializer.save()
        context = {'obj': category_serializer.data, 'status': status.HTTP_201_CREATED}
        return SuccessJsonResponse(context)

    context = {'obj': category_serializer.errors, 'status': status.HTTP_400_BAD_REQUEST}
    return JsonResponse(context)


@login_required
@api_view(['POST'])
def archive_category(request):
    """
    Archives a category
    """

    data = request.data
    Category.objects.filter(pk=data.get('category_id')).update(archived=True)

    return SuccessJsonResponse()


@login_required
@api_view(['GET'])
def category_linqs(request):
    """
    Return all category linQs when the category name is clicked
    """

    # print(flush=True)

    data = request.GET
    category_id = data.get('category_id')
    is_new = data.get('is_new')  # has the category name been clicked yet?

    serialized_linq_list = LinqsCache(category_id).serialized_objects()

    if is_new == 'true':
        Category.objects.filter(pk=category_id).update(new_item=False)

    return SuccessJsonResponse({
        'categoryLinqs': serialized_linq_list,
    })


@login_required
@api_view(['POST'])
def add_linq(request):
    """
    Add a new LinQ, creates Label and URLs
    """

    data = request.data
    cat_id = data.get('category_id')
    label = data.get('label')
    url_list = data.get('url').split(',')

    instance = LinqLabel.objects.create(category_id=cat_id, name=label)

    url_list_objs = (
        LinqUrl(label=instance, url=x) for x in url_list
    )

    LinqUrl.objects.bulk_create(objs=(url_obj for url_obj in url_list_objs))

    LinqsCache(cat_id).set_needs_caching()

    return SuccessJsonResponse({
        'newLinq': LinqLabelSerializer(instance).data,
    })


@login_required
@api_view(['POST'])
def archive_linq(request):
    """
    Archive a new LinQ
    """

    data = request.data
    LinqLabel.objects.filter(pk=data.get('linq_id')).update(archived=True)

    LinqsCache(data.get("category_id")).set_needs_caching()

    return SuccessJsonResponse()


@login_required
@api_view(['GET'])
def search_linq(request):
    """
    Search LinQs given a search term
    """

    term = request.GET.get("search_term")
    linq_list = LinqLabel.objects.filter(name__icontains=term).select_related('category').prefetch_related('linqurl_set')

    return SuccessJsonResponse({
        "searchedLinqs": LinqLabelSerializer(instance=linq_list, many=True).data,
    })


@login_required
@api_view(['POST'])
def update_linq(request):
    """
    Update LinQ label or urls (add/remove)
    """

    data = request.data

    linq = LinqLabel.objects.get(pk=data["linq_id"])
    linq.name = data["linq_name"]
    linq.save()

    # create all the new urls
    LinqUrl.objects.bulk_create(
        (LinqUrl(
            label_id=data["linq_id"],
            url=url["url"]
        ) for url in data["urls"] if not url.get("id"))
    )

    # archive linq urls
    LinqUrl.objects.filter(id__in=data.get("archived_id_list")).update(archived=True)

    linq.refresh_from_db()

    LinqsCache(linq.category.id).set_needs_caching()

    return SuccessJsonResponse({
        "linq": LinqLabelSerializer(linq).data,
    })

snipps/app/views/snippets.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from rest_framework.decorators import api_view
from rest_framework import status

from app.models import SnippetCategory, SnippetLabel, Snippet
from app.serializers import SnippetCategorySerializer, SnippetLabelSerializer
from app.utils import SuccessJsonResponse


@login_required()
def snippets(request):

    categories = SnippetCategory.objects.filter(user=request.user)

    context = {
        'init_js_data': {
            'categories': SnippetCategorySerializer(categories, many=True).data
        }
    }

    if categories:
        label_list = SnippetLabel.objects.filter(category_id=categories[0].id).select_related('category').prefetch_related('snippet')

        context['init_js_data'].update({
            'initSelectedSnippets': SnippetLabelSerializer(instance=label_list, many=True).data
        })

    return render(request, 'app/snippets.html', context)


# API VIEWS
@login_required
@api_view(['POST'])
def add_snippet_category(request):
    """
    Add a new category
    """

    category_count = SnippetCategory.objects.count()
    data = {'user': request.user.id, **request.data}

    # only when creating a category for the firs time
    if category_count == 0:
        data.update({'new_item': False})

    category_serializer = SnippetCategorySerializer(data=data)

    if category_serializer.is_valid():
        category_serializer.save()
        context = {'obj': category_serializer.data, 'status': status.HTTP_201_CREATED}
        return SuccessJsonResponse(context)

    context = {'obj': category_serializer.errors, 'status': status.HTTP_400_BAD_REQUEST}
    return JsonResponse(context)


@login_required
@api_view(['POST'])
def archive_snippet_category(request):
    """
    Archives a category
    """

    data = request.data
    SnippetCategory.objects.filter(pk=data.get('category_id')).update(archived=True)

    return SuccessJsonResponse()


@login_required
@api_view(['GET'])
def category_snippets(request):
    """
    Return all category Snippets/Labels when the category name is clicked
    """

    # print(flush=True)

    data = request.GET
    category_id = data.get('category_id')
    is_new = data.get('is_new')  # has the category name been clicked yet?

    snippets_list = SnippetLabel.objects.filter(category_id=category_id).select_related('category').prefetch_related('snippet')

    if is_new == 'true':
        SnippetCategory.objects.filter(pk=category_id).update(new_item=False)

    return SuccessJsonResponse({
        'categoryLabels': SnippetLabelSerializer(instance=snippets_list, many=True).data,
    })


@login_required
@api_view(['POST'])
def add_snippet_label(request):
    """
    Add a new category
    """

    snippet = Snippet.objects.create(value='"Add snippet here"')

    data = {
        'user': request.user.id,
        "name": request.data.get("name"),
        "category": int(request.data.get("category_id")),
        "snippet": snippet.id
    }

    category_serializer = SnippetLabelSerializer(data=data)

    if category_serializer.is_valid():
        category_serializer.save()
        context = {'obj': category_serializer.data, 'status': status.HTTP_201_CREATED}
        return SuccessJsonResponse(context)

    context = {'obj': category_serializer.errors, 'status': status.HTTP_400_BAD_REQUEST}
    return JsonResponse(context)


@login_required
@api_view(['PUT'])
def archive_label(request):
    """
    Archive a new LinQ
    """

    data = request.data
    SnippetLabel.objects.filter(pk=data.get('label_id')).update(archived=True)

    return SuccessJsonResponse()


# API VIEWS
@login_required
@api_view(['PUT'])
def update_snippet(request):
    """
    Update Snippet

    Will update the snippet code or the code type, but no both at the same time
    """

    snippet_id = request.data.get("snippet_id")
    snippet_value = request.data.get("snippet_value")
    snippet_type = request.data.get("snippet_type")

    Snippet.objects.filter(pk=snippet_id).update(value=snippet_value, type=snippet_type)

    return SuccessJsonResponse()

snipps/app/templates/app/base.html
{% load static %}
{% load manifest %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        {% block meta %}
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
            <!-- Meta, title, CSS, favicons, etc. -->
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">
        {% endblock meta %}

        <title>Snipp-Labs | {% block title %}{% endblock %}</title>

        <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

        <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
        <link href="{% manifest 'base.css' %}" rel="stylesheet" />

        {% block stylesheets %}
        {% endblock stylesheets %}

    {% endblock head %}
</head>

<body content="text/html">

    {% block body %}

        <div class="container-fluid">
            {% include "app/navbar.html" %}

            {% block content %}
            {% endblock content %}
        </div>

    {% endblock body %}

    <script type="text/javascript" src="{% manifest 'runtime.js' %}" ></script>
    <script type="text/javascript" src="{% manifest 'vendor.js' %}" ></script>
    <script type="text/javascript" src="{% manifest 'base.js' %}" ></script>
    
    {% block javascript_footer %}
    {% endblock javascript_footer %}

</body>
</html>

snipps/app/templates/app/linqs.html
{% extends 'app/base.html' %}
{% load manifest %}
{% load js_data %}


{% block title %} Linqs {% endblock title %}


{% block stylesheets %}
    {{ block.super }}
    <link href="{% manifest 'linqs.css' %}" rel="stylesheet" />
{% endblock stylesheets %}


{% block content %}

    <div class="row">
        <div id="linqs-root"></div>
    </div>
    

{% endblock content %}


{% block javascript_footer %}
    {{ block.super }}
    {{ init_js_data | js_data }}
    <script type="text/javascript" src="{% manifest 'linqs.js' %}" ></script>
{% endblock %}

snipps/app/templates/app/navbar.html
{% load static %}

<!-- <div class="border-bottom border-2 border-info mb-3">
    <ul class="nav justify-content-center">
        <li class="nav-item text-start">
            <a class="nav-link text-info" href="{% url 'app:linqs' %}">Linqs</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="#">Snippets</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="#"> Logout</a>
        </li>
    </ul>

    <div>
        <div class="text-center"><a class="nav-link text-info" href="{% url 'app:linqs' %}">Linqs</a></div>
        <div class="text-center"><a class="nav-link text-info" href="{% url 'app:linqs' %}">Linqs</a></div>
    </div>
</div> -->

<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3 py-0 border-bottom border-1 border-primary">
    <div class="container-fluid">

      <a class="navbar-brand" href="{% url 'app:linqs' %}">
{#          <img src="{% static 'logo-2.png' %}" alt="Snipp-Labs Logo" width="20" height="20"> &nbsp; | &nbsp;#}
          <i class="fas fa-terminal text-dark"></i>
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">

        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link {% if '/linqs/' in request.path %} text-primary pb-0 {% endif%}" aria-current="page" href="{% url 'app:linqs' %}">LinQs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if '/snippets/' in request.path %} text-primary pb-0 {% endif%}" href="{% url 'app:snippets' %}">Snippets</a>
{#            <a class="nav-link {% if '/snippets/' in request.path %} text-primary border-bottom border-primary pb-0 {% endif%}" href="{% url 'app:snippets' %}">Snippets</a>#}
          </li>
        </ul>

        <ul class="navbar-nav ms-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{user.username}}
                </a>
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-sm-end" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'admin:index' %}">Django Admin</a></li>
                  <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                </ul>
              </li>      
          </ul>
      </div>
    </div>
  </nav>

snipps/app/templates/app/snippets.html
{% extends 'app/base.html' %}
{% load manifest %}
{% load js_data %}


{% block title %} Snippets {% endblock title %}


{% block stylesheets %}
    {{ block.super }}
    <link href="{% manifest 'snippets.css' %}" rel="stylesheet" />
{% endblock stylesheets %}


{% block content %}

    <div class="row">
        <div id="snippets-root"></div>
    </div>
    

{% endblock content %}


{% block javascript_footer %}
    {{ block.super }}
    {{ init_js_data | js_data }}
    <script type="text/javascript" src="{% manifest 'snippets.js' %}" ></script>
{% endblock %}